# analysis_options.yaml - Configured for production-ready Flutter app
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  
  errors:
    # Treat these as errors
    invalid_assignment: error
    missing_required_param: error
    missing_return: error
    
    # Warnings
    unused_import: warning
    unused_local_variable: warning
    
    # Info (allow but show)
    avoid_print: info
    use_build_context_synchronously: info
    deprecated_member_use: info

linter:
  rules:
    # Enabled rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_super_parameters
    - valid_regexps
    
    # Disabled for development convenience
    # - avoid_print  # Allow print for debugging
    # - use_build_context_synchronously  # Allow with mounted checks
